# Generated by Django 2.0.5 on 2018-09-22 15:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpDetailsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.TextField()),
                ('DOB', models.DateTimeField(default=datetime.datetime(2018, 9, 22, 15, 13, 44, 342029, tzinfo=utc))),
                ('PermanentAddress', models.CharField(max_length=200)),
                ('Dateofjoining', models.DateTimeField(default=datetime.datetime(2018, 9, 22, 15, 13, 44, 342029, tzinfo=utc))),
                ('Designation', models.TextField()),
                ('Department', models.TextField()),
                ('EmployeeId', models.TextField()),
                ('EmailId', models.TextField()),
                ('Gender', models.TextField()),
                ('Phonenumber', models.TextField()),
                ('Status', models.TextField()),
            ],
        ),
    ]
