# Generated by Django 2.0.5 on 2018-09-23 00:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('EmpDetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdetailsmodel',
            name='DOB',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 23, 0, 31, 15, 348666, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='empdetailsmodel',
            name='Dateofjoining',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 23, 0, 31, 15, 349670, tzinfo=utc)),
        ),
    ]
