# Generated by Django 2.0.5 on 2018-09-23 09:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('EmpDetails', '0003_auto_20180923_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdetailsmodel',
            name='DOB',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 23, 9, 11, 49, 821840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='empdetailsmodel',
            name='Dateofjoining',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 23, 9, 11, 49, 821840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='empdetailsmodel',
            name='Gender',
            field=models.TextField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
