# Generated by Django 2.0.5 on 2018-09-23 09:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('EmpDetails', '0004_auto_20180923_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdetailsmodel',
            name='DOB',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 23, 9, 21, 11, 876688, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='empdetailsmodel',
            name='Dateofjoining',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 23, 9, 21, 11, 876688, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='empdetailsmodel',
            name='Phonenumber',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='empdetailsmodel',
            name='Status',
            field=models.TextField(choices=[('A', 'Active'), ('I', 'Inactive')]),
        ),
    ]
