# Generated by Django 2.0.5 on 2018-09-23 10:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('EmpDetails', '0006_auto_20180923_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='empdetailsmodel',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empdetailsmodel',
            name='DOB',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 23, 10, 11, 22, 34420, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='empdetailsmodel',
            name='Dateofjoining',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 23, 10, 11, 22, 34420, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='empdetailsmodel',
            name='EmployeeId',
            field=models.TextField(),
        ),
    ]
