# Generated by Django 2.0.5 on 2018-09-23 10:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('EmpDetails', '0008_auto_20180923_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empdetailsmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='empdetailsmodel',
            name='DOB',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 23, 10, 13, 26, 527682, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='empdetailsmodel',
            name='Dateofjoining',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 23, 10, 13, 26, 527682, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='empdetailsmodel',
            name='EmployeeId',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
