# Generated by Django 2.0.5 on 2018-09-23 10:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('EmpDetails', '0009_auto_20180923_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdetailsmodel',
            name='DOB',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 23, 10, 23, 39, 290643, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='empdetailsmodel',
            name='Dateofjoining',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 23, 10, 23, 39, 290643, tzinfo=utc)),
        ),
    ]
