# Generated by Django 2.0.5 on 2018-09-23 10:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpDetailsModel',
            fields=[
                ('FullName', models.TextField()),
                ('DOB', models.DateTimeField(default=datetime.datetime(2018, 9, 23, 10, 32, 0, 770921, tzinfo=utc))),
                ('PermanentAddress', models.CharField(max_length=200)),
                ('Dateofjoining', models.DateTimeField(default=datetime.datetime(2018, 9, 23, 10, 32, 0, 770921, tzinfo=utc))),
                ('Designation', models.TextField()),
                ('Department', models.TextField()),
                ('EmployeeId', models.TextField(primary_key=True, serialize=False)),
                ('EmailId', models.EmailField(max_length=254)),
                ('Gender', models.TextField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('Phonenumber', models.TextField(max_length=10)),
                ('Status', models.TextField(choices=[('A', 'Active'), ('I', 'Inactive')])),
            ],
        ),
    ]
